version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq_for_creatio
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASSWORD: "guest"
    networks:
      - network
networks:
  network: {}